feat : TailwindCSS and React-Router
quickank1t/shoping_site pull request #17
Opened 2023-09-04 15:38 UTC by WiseyXD

Fixed eslint errors

2023-09-04 16:28 UTC, quickank1t requested changes

2023-09-04 16:28 UTC, quickank1t commented on package.json
> +    "localforage": "^1.10.0",
why do you need this dependency?

2023-09-04 16:28 UTC, quickank1t commented on package.json
> +    "match-sorter": "^6.3.1",
why do you need this dependency?

2023-09-04 16:28 UTC, quickank1t commented on package.json
> +    "sort-by": "^1.2.0"
why do you need this dependency?

2023-09-04 16:28 UTC, quickank1t commented on package.json
> +    "tailwindcss": "^3.3.3",
tailwind should be in another pr not the same..

2023-09-04 16:28 UTC, quickank1t commented on src/Components/Footer.jsx
> +import React from "react";
fix eslint issues

2023-09-04 16:29 UTC, quickank1t requested changes

2023-09-04 16:29 UTC, quickank1t commented on index.html
> +		<div id="root">Not Rendered</div>
why do you need not rendered ?

2023-09-04 18:04 UTC, WiseyXD commented on index.html
> +		<div id="root">Not Rendered</div>
To know wether the app is getting injected into the rrot or not

2023-09-04 18:05 UTC, WiseyXD commented on package.json
> +    "sort-by": "^1.2.0"
These were all the dependencies mentioned in the react router docs 

You can refer the docs here : https://reactrouter.com/en/main/start/tutorial

2023-09-04 18:06 UTC, WiseyXD commented on package.json
> +    "match-sorter": "^6.3.1",
These were all the dependencies mentioned in the react router docs

You can refer the docs here : https://reactrouter.com/en/main/start/tutorial

2023-09-04 18:06 UTC, WiseyXD commented on package.json
> +    "localforage": "^1.10.0",
These were all the dependencies mentioned in the react router docs

You can refer the docs here : https://reactrouter.com/en/main/start/tutorial

2023-09-05 13:25 UTC, WiseyXD commented
Sending in new pull request

2023-09-06 06:56 UTC, quickank1t commented
changes are not working.

<img width="1550" alt="Screenshot 2023-09-06 at 08 52 48" src="https://github.com/quickank1t/shoping_site/assets/18901852/dbe23921-5920-403d-8d55-63262711cc6c">

also when i request any change you cannot resolve it, just comment it and i will decide if i have to resolve it or not.

also, i requested you to do two prs for two changes.. still i see only one for both tailwind and route

2023-09-06 06:57 UTC, quickank1t commented
closing this pr. make two PRs one for tailwind and the other for routes with Clark

2023-09-06 06:57 UTC, closed without merging